const MaxHeap = require('./src/max-heap');
const Node = require('./src/node');
const h = new MaxHeap();
const node = new Node (12,50);
window.h = h;
h.push(15, 42);
h.push(13, 0);
h.push(14, 100);
alert(h.size);
h.pop();
alert(h.size);