const Queue = require('./src/queue');
const MaxHeap = require('./src/max-heap');
const Node = require('./src/node');
const h = new MaxHeap();
const node = new Node (12,50);
const q = new Queue();
window.h = h;
q.push(0, 1);
q.push(1, 2);
q.push(2, 3);
q.shift();
q.shift();
q.shift();